(Rec-15) Сверстать страницу регистрации + логика регистрации (поход в ручку)
Sergey-Pavlov809/Pac-Man pull request #14
Opened 2023-12-22 16:58 UTC by AlDmitOl

### Какую задачу решаем

 Сверстать страницу регистрации + логика регистрации (поход в ручку)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-12-23 12:02 UTC, rkeyrice commented on packages/client/src/routes.ts
> +  registration: (): string => '/registration',
уже есть роут для регистрации

2023-12-23 12:02 UTC, rkeyrice commented on packages/client/src/services/y-api-service.ts
> +import axios, { AxiosResponse } from 'axios'
думаю , лучше фетч, аксиос бы снести вообще, после добавления редакса ртк там будет

2023-12-23 12:02 UTC, rkeyrice commented on packages/client/src/main.tsx
> +import Registration from './pages/registration/Registration'
папку бы тоже с большой буквы, как и остальные

2023-12-23 12:02 UTC, rkeyrice commented on packages/client/src/pages/registration/Registration.tsx
> +          // className={css.form}
удалить

2023-12-23 15:33 UTC, AnastasiaPlague requested changes

2023-12-23 15:33 UTC, AnastasiaPlague commented on packages/client/src/main.tsx
> +  },
уже заведен роут для реги - sign-up

2023-12-23 15:33 UTC, AnastasiaPlague commented on packages/client/src/pages/registration/Registration.tsx
> +                message: 'Пожалуйста, подтвердите свой пароль !',
```suggestion
                message: 'Пожалуйста, подтвердите свой пароль!',
```

2023-12-23 22:20 UTC, AnastasiaPlague approved these changes

2023-12-24 19:06 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечаний
Поздравляю, апрув 🚀 

Хорошего дня :)

2023-12-24 19:06 UTC, IvanPeleshok commented on packages/client/src/pages/Sign-up/Sign-up.tsx
> +      console.log('Result register', response.data)
Нужен ли отладочный код в деве?

2023-12-24 19:06 UTC, IvanPeleshok commented on packages/client/src/services/y-api-service.ts
> +    return fetch(`${Y_API_BASE_URL}/auth/signup`, {
Можно обратить внимание на библиотеку axios для отправки запросов: https://axios-http.com/ru/
Работа с этой библиотекой сильно облегчит вам жизнь
Дополнительно можно сформировать экземпляр с предустановленным конфигом запроса: https://axios-http.com/ru/docs/instance

2023-12-26 16:32 UTC, merged