Add game start page
Sergey-Pavlov809/Pac-Man pull request #17
Opened 2023-12-23 16:06 UTC by AnastasiaPlague

### Какую задачу решаем
Экран начала игры

- Перетасовала руты, чтоб добавиьт на чать страницы шапку и подвал
- Шапка и подвал убраны с лендинга

2023-12-23 23:13 UTC, Sergey-Pavlov809 approved these changes

2023-12-24 07:50 UTC, AlDmitOl commented on packages/client/src/components/layout/AppLayout/AppLayout.tsx
> +  <Layout className={css.root}>
У меня футер как то странно висит по средине экрана при скролле. В докуметации antd показывалось, что можно обернуть все во Flex:
<Flex gap="middle" wrap="wrap">
  <Layout className={css.root}>
  {disableHeader ? null : <Header />}
  <Layout.Content>
    <Outlet />
  </Layout.Content>
  <Footer />
</Layout>
Так же если нам нужно, что бы меню/футер всегда были на экране, то в документакии предлагалось сделать это так:

<Header style={{
position: 'sticky',
top: 0,
zIndex: 1,
width: '100%',
display: 'flex',
alignItems: 'center', }}>

Соответственно футер:

<Footer style={{
position: 'sticky',
bottom: 0,
zIndex: 1,
width: '100%',
display: 'flex',
alignItems: 'center', }}>

2023-12-24 07:57 UTC, AlDmitOl commented on packages/client/src/components/layout/AppLayout/AppLayout.tsx
> +  </Layout>
У меня футер как то странно висит по средине экрана при скролле. В докуметации antd показывалось, что можно обернуть все во Flex:
```
<Flex gap="middle" wrap="wrap">
  <Layout className={css.root}>
  {disableHeader ? null : <Header />}
  <Layout.Content>
    <Outlet />
  </Layout.Content>
  <Footer />
  </Layout>
</Flex>
```

Так же если нам нужно, что бы меню/футер всегда были на экране, то в документакии предлагалось сделать это так:

```
<Header style={{
  position: 'sticky',
  top: 0,
  zIndex: 1,
  width: '100%',
  display: 'flex',
  alignItems: 'center', }}>
```

Соответственно футер:

```
<Footer style={{
position: 'sticky',
bottom: 0,
zIndex: 1,
width: '100%',
display: 'flex',
alignItems: 'center', }}>
```

2023-12-24 08:47 UTC, AlDmitOl commented on packages/client/src/main.tsx
> +        element: <App />,
Может тоже?
```element: <Main />,```
А то корневой путь ведет сйчас на непонятную страницу, по идее тут тоже главная должна быть.

2023-12-24 08:55 UTC, AlDmitOl commented on packages/client/src/pages/Game/const.tsx
> +      'Очки зарабатываются за поедание шариков, и призраков. Игрок стремится достичь максимального счета, прежде чем закончатся все жизни.',
Может пока убрать 'и призраков'? Если у нас не будет механизма поедания, то это не нужно, если будет, то тогда наверное нужно сделать описание каким можно съесть призрака

2023-12-24 08:57 UTC, AlDmitOl commented on packages/client/src/pages/Main/Main.tsx
> +            <Button type="primary" size="large">
Раз появилась страница играть, то может добавить на нее ссылку?

2023-12-24 09:21 UTC, AnastasiaPlague commented on packages/client/src/components/layout/AppLayout/AppLayout.tsx
> +  </Layout>
Если есть баг верстки - покажи скрин или как его воспроизвести. 
Цель была, чтоб подвал просто всегда был внизу страницы. Сам лейаут и есть флексовый элемент. Я не очень понимаю, к чему ты клонишь

2023-12-24 09:24 UTC, AnastasiaPlague commented on packages/client/src/main.tsx
> +        element: <App />,
Зачем? Чтобы было две одинаковые страницы по двум путям?)

2023-12-24 10:38 UTC, rkeyrice commented on packages/client/src/pages/Game/const.tsx
> +      'Очки зарабатываются за поедание шариков, и призраков. Игрок стремится достичь максимального счета, прежде чем закончатся все жизни.',
Должно быть поедание)

2023-12-24 11:24 UTC, AnastasiaPlague commented on packages/client/src/components/layout/AppLayout/AppLayout.tsx
> +  </Layout>
Увидела проблему с подвалом на узком экране. Поправлю

2023-12-24 11:59 UTC, rkeyrice approved these changes

2023-12-24 12:26 UTC, AlDmitOl commented on packages/client/src/main.tsx
> +        element: <App />,
ну можно автоматический переход  сделать тогда, при открытии страницы '/', на '/main'. Просто сейчас открываешь, например, http://localhost:3000/ и видишь непонятную надпись, а по идее тут должна быть главная страница, или тут у нас будет еще какая-то страница?

2023-12-24 12:28 UTC, AlDmitOl commented on packages/client/src/pages/Game/const.tsx
> +      'Очки зарабатываются за поедание шариков, и призраков. Игрок стремится достичь максимального счета, прежде чем закончатся все жизни.',
Тогда нужно наверное сделать описание каким образом можно съесть призрака?

2023-12-24 12:58 UTC, AnastasiaPlague commented on packages/client/src/main.tsx
> +        element: <App />,
на страницу с лендингом (main) попадает пользователь после авторизации, см скриншот
![image](https://github.com/Sergey-Pavlov809/Pac-Man/assets/51404589/0e2efde8-d1ba-43f3-880d-a2e08007ab08)

значит на / ее быть не должно. и на / наверно можно размещать страницу логина? )

вообще это конечно не относится к задаче "сделать стартовый экран игры", но раз уж начали обсуждать)

2023-12-24 12:59 UTC, AnastasiaPlague commented on packages/client/src/pages/Game/const.tsx
> +      'Очки зарабатываются за поедание шариков, и призраков. Игрок стремится достичь максимального счета, прежде чем закончатся все жизни.',
я предлагаю не бежать впереди паровоза, и текстовки подбить по факту реализации механик игры. мы же все понимаем, что это наброски пока?

2023-12-24 15:02 UTC, dmitry-aladzyeu approved these changes

2023-12-24 15:04 UTC, AlDmitOl approved these changes

2023-12-24 19:30 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть замечания, предлагаю доработать

Хорошего дня :)

2023-12-24 19:30 UTC, IvanPeleshok commented on packages/client/src/components/layout/AppLayout/AppLayout.tsx
> +    {disableHeader ? null : <Header />}
```
{disableHeader && <Header />}

2023-12-24 19:30 UTC, IvanPeleshok commented on packages/client/src/pages/Game/GamePage.tsx
> +    setStatus('in_progress')
Предлагаю вынести в константы in_progress / idle / finish и переиспользовать в разных модулях приложения

2023-12-24 19:30 UTC, IvanPeleshok commented on packages/client/src/pages/Game/GameStart.tsx
> +        actions={[
Предлагаю немного оптимизировать данный код следующим образом:
https://react.dev/reference/react/useMemo
```
const actionButtons = useMemo(() => {
  return [
   currentStep < GAME_RULES.length - 1 
   && (
      <Button key="next" type="primary" onClick={handleNext}>
        Далее
      </Button>
   ),
   currentStep === GAME_RULES.length - 1
   && (
      <Button key="start" type="primary" onClick={handleReady}>
        Начать игру
      </Button>
   ),
  ...
  ].filter(Boolean)
}, [currentStep])


return (
  <Card actions={actionsButtons} />
)

2023-12-24 19:30 UTC, IvanPeleshok commented on packages/client/src/pages/Game/GameStart.tsx
> +                <Button key="next" type="primary" onClick={handleNext()}>
handleNext() - будет вызываться во время рендера элемента
Для того, чтобы функция вызывалась во время события необходимо:
1) onClick={handleNext} - передавать ссылку на функцию
2) onClick={() => handleNext()} - передавать колбек функцию

Ниже аналогично (предлагаю поправить)

2023-12-24 19:41 UTC, AnastasiaPlague commented on packages/client/src/pages/Game/GameStart.tsx
> +                <Button key="next" type="primary" onClick={handleNext()}>
Не будет, это каррированная функция :)

2023-12-24 19:44 UTC, AnastasiaPlague commented on packages/client/src/components/layout/AppLayout/AppLayout.tsx
> +    {disableHeader ? null : <Header />}
предпочитаю использовать тернарники в развернутом виде в рендере, как по мне, читается лучше чем шортхенд

2023-12-25 10:04 UTC, IvanPeleshok commented on packages/client/src/pages/Game/GameStart.tsx
> +                <Button key="next" type="primary" onClick={handleNext()}>
Ага, не заметил

2023-12-25 10:04 UTC, IvanPeleshok approved these changes
Всё супер!
Апрув
Хорошего дня :)

2023-12-25 10:38 UTC, merged