created normal map and animated packmen
Sergey-Pavlov809/Pac-Man pull request #19
Opened 2023-12-24 15:27 UTC by rkeyrice

- Сделал нормальную карту
- Анимировал пакмена

https://github.com/Sergey-Pavlov809/Pac-Man/assets/145926924/dc09def8-6776-41a3-b7c8-6e8011660aea

2023-12-24 19:10 UTC, AnastasiaPlague requested changes

2023-12-24 19:10 UTC, AnastasiaPlague commented on packages/client/src/pages/Game/Player.tsx
> +    }
есть возможность вынести в именованные методы? так сходу не супер очевидно, что тут происходит. возможно коммент тоже подойдет

2023-12-25 08:27 UTC, rkeyrice commented on packages/client/src/pages/Game/Player.tsx
> +    }
вынесу)

2023-12-25 08:45 UTC, AnastasiaPlague approved these changes

2023-12-25 13:55 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечаний
Поздравляю, апрув 🚀 

Оставил комментарии по улучшению реализации фичи

Хорошего дня :)

2023-12-25 13:55 UTC, IvanPeleshok commented on packages/client/src/pages/Game/Player.tsx
> +    if (this.radians < 0 || this.radians > 0.75) {
Чтобы при прочтении кода не было магических чисел и вопросов почему такое значение - предлагаю выносить их в переменную с контекстным названием 
Пример: DEFAULT_RADIANS

2023-12-25 14:21 UTC, merged