Dreft Feat(REC-34): Добавил Redux toolkit
Sergey-Pavlov809/Pac-Man pull request #22
Opened 2023-12-26 17:47 UTC by Sergey-Pavlov809

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-12-27 08:54 UTC, AnastasiaPlague requested changes

2023-12-27 08:54 UTC, AnastasiaPlague commented on package-lock.json
а зачем его удалять?

2023-12-27 08:54 UTC, AnastasiaPlague commented on packages/client/src/store/index.ts
> +  },
```suggestion
  reducer: {
     auth:  authReducer,
  },
```

2023-12-27 08:54 UTC, AnastasiaPlague commented on packages/client/src/hooks/useAppDispatch/index.ts
> +export const useAppDispatch = (): AppDispatch => useDispatch<AppDispatch>()
```suggestion
export const useAppDispatch = (): AppDispatch => useDispatch<AppDispatch>
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
```

см https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks

2023-12-27 08:54 UTC, AnastasiaPlague commented on packages/client/src/store/modules/auth/reducer.ts
> +export const fetchUserData = createAsyncThunk('fetchUserData', async () => {
```suggestion
export const fetchUserData = createAsyncThunk('auth/fetchUserData', async () => {
```

2023-12-27 08:54 UTC, AnastasiaPlague commented on packages/client/src/store/modules/auth/reducer.ts
> +
добавить селектор на слайс

```javascript
export const selectAuth = (state: RootState) => state.auth
```

2023-12-27 08:54 UTC, AnastasiaPlague commented on packages/client/src/store/types.ts
> +export type AppDispatch = typeof store.dispatch
Добавить типизированный стейт
```javascript
export type RootState = ReturnType<typeof store.getState>
```

см https://redux-toolkit.js.org/tutorials/typescript#define-root-state-and-dispatch-types

2023-12-27 08:54 UTC, AnastasiaPlague commented on packages/client/src/store/modules/auth/reducer.ts
> +    })
состояние лоадинга пригодилось бы, стоит добавить

2023-12-27 08:54 UTC, AnastasiaPlague commented on packages/client/src/store/modules/auth/reducer.ts
> +  return response
предлагаю ловить ошибки в редаксе, в сервисе не ловить

https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors

2023-12-28 16:04 UTC, AnastasiaPlague requested changes

2023-12-28 16:04 UTC, AnastasiaPlague commented on packages/client/src/hooks/useAppDispatch/index.ts
> +export const useAppDispatch = (): AppDispatch => useDispatch<AppDispatch>()
```suggestion
export const useAppDispatch = (): AppDispatch => useDispatch
```

см https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks

2023-12-28 16:04 UTC, AnastasiaPlague commented on packages/client/src/store/index.ts
> +    authReducer,
```suggestion
    auth: authReducer,
```

2023-12-28 16:04 UTC, AnastasiaPlague commented on packages/client/src/store/modules/auth/reducer.ts
> +)
```suggestion
export const fetchUserData = createAsyncThunk(
  'auth/fetchUserData',
  async (_, { rejectWithValue }) => {
    try {
      const response = await yApiService.getUser()

      return response
    } catch (error) {
      message.error(`Ошибка загрузки файла: ${error}`)
      return rejectWithValue(err.response.data)
    }
  }
)
```

иначе в экстраРедьюсер с ошибкой не попадет

2023-12-28 16:05 UTC, AnastasiaPlague commented on packages/client/src/store/modules/auth/reducer.ts
> +      message.error(`Ошибка загрузки файла: ${error}`)
также не очень понятно, почему такая текстовка, если мы юзера просим

2023-12-29 15:23 UTC, AnastasiaPlague approved these changes

2023-12-29 18:32 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечаний
Поздравляю, апрув 🚀 

Хорошего дня :)

2023-12-30 10:01 UTC, merged