feat: add leaderboard page
Sergey-Pavlov809/Pac-Man pull request #24
Opened 2024-01-03 12:43 UTC by DaoNik

### Какую задачу решаем
Сверстать страницу лидерборда

### Скриншоты/видяшка (если есть)
![Screenshot 2024-01-03 at 15 38 21](https://github.com/Sergey-Pavlov809/Pac-Man/assets/55061470/93396972-c069-4463-a73b-9270ea33cea4)

2024-01-07 10:32 UTC, AnastasiaPlague requested changes

2024-01-07 10:32 UTC, AnastasiaPlague commented on packages/client/src/index.css
> +}
по идее лишнее, в резете анта уже есть

2024-01-07 10:32 UTC, AnastasiaPlague commented on packages/client/src/pages/LeaderBoard/LeaderBoard.module.css
> +}
я бы отклеила таблицу от шапки пикселей на 24

2024-01-07 10:32 UTC, AnastasiaPlague commented on packages/client/src/pages/LeaderBoard/LeaderBoard.tsx
> +        pageSizeOptions: [5, 10, 15, 20],
апи яндекса поддерживает пагинацию, смотрел? 
если да, можно ли кастомизировать то, где выбираешь кол-во рядов 15 / page - чтоб пейдж по-русски было?

2024-01-13 16:55 UTC, DaoNik commented on packages/client/src/pages/LeaderBoard/LeaderBoard.tsx
> +        pageSizeOptions: [5, 10, 15, 20],
На созвоне обсуждали, что апи для лидербоарда сами будем писать(по крайней мере для получения списка пользователей), если будет проще без него могу удалить, текст поменял

2024-01-13 17:27 UTC, AnastasiaPlague approved these changes

2024-01-14 14:13 UTC, merged