(REC-31) Добавить Service Workers
Sergey-Pavlov809/Pac-Man pull request #25
Opened 2024-01-07 17:12 UTC by AlDmitOl

### Какую задачу решаем

 Добавить Service Workers

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-01-09 08:34 UTC, AnastasiaPlague requested changes

2024-01-09 08:34 UTC, AnastasiaPlague commented on packages/client/src/hooks/useAppDispatch/index.ts
> +export const useAppDispatch = (): AppDispatch => useDispatch<AppDispatch>()
```suggestion
export const useAppDispatch: () => AppDispatch = useDispatch
```

2024-01-09 08:34 UTC, AnastasiaPlague commented on packages/client/src/serviceWorker.ts
> +  }
```suggestion
  return req.url.match(/^http/)
```

2024-01-09 08:34 UTC, AnastasiaPlague commented on packages/client/src/serviceWorker.ts
> +]
это только руками можно контролировать? 
то есть при добавлении нового ассета надо идти сюда и руками дописать?

2024-01-09 08:34 UTC, AnastasiaPlague commented on packages/client/src/serviceWorker.ts
> +const FETCH_NETWORK_TIMEOUT = 15000
давай в соседний файл положим, какой-нить const

2024-01-09 08:34 UTC, AnastasiaPlague commented on packages/client/src/serviceWorker.ts
> +const FETCH_NETWORK_TIMEOUT = 15000
так рекомендуют делить таймауты?

2024-01-09 15:06 UTC, AlDmitOl commented on packages/client/src/serviceWorker.ts
> +  }
Изначально думал так же, но match может вернуть null, что приведет к ошибке типизации, так как функция должна boolean вернуть, но как вариант можем сделать
```return !!req.url.match(/^http/);```

2024-01-09 15:27 UTC, AlDmitOl commented on packages/client/src/serviceWorker.ts
> +]
В практике написано:
``Есть много способов динамической подстановки путей: через Webpack, через NodeJS, смешанные.``
но так как после билда в ассетах у нас только 2 картинки, то наверное на данном этапе не вижу большого смысла, что-то мудрить и если не планируем добавлять в кеш больше 10 ассетов, то я бы предложил оставить так

2024-01-09 15:41 UTC, AlDmitOl commented on packages/client/src/serviceWorker.ts
> +const FETCH_NETWORK_TIMEOUT = 15000
Вот тут не понял, что ты предлагаешь положить? Можешь пояснить?

2024-01-09 16:02 UTC, AlDmitOl commented on packages/client/src/serviceWorker.ts
> +const FETCH_NETWORK_TIMEOUT = 15000
Статью не могу найти на которую опирался, но в разных местах встречал про таймауты в запросах.
Например: https://subscription.packtpub.com/book/web-development/9781786465290/1/ch01lvl1sec17/handling-request-timeouts
Но прям рекомендацию наверное нет. Но мне показалось разумным делать запросы и если долго нету ответов от сервера выдавать кэш. Чем медленнее появляется страница, тем больше вероятность, что пользователь не дождется полного открытия и просто сайт закроет. А что смущает?

2024-01-09 19:54 UTC, AnastasiaPlague commented on packages/client/src/serviceWorker.ts
> +]
это пока их так мало, а дальше как, ассеты еще не все есть же?

2024-01-09 19:55 UTC, AnastasiaPlague commented on packages/client/src/serviceWorker.ts
> +const FETCH_NETWORK_TIMEOUT = 15000
все константы вынести из файла, оставить только логику тут

2024-01-09 19:57 UTC, AnastasiaPlague commented on packages/client/src/serviceWorker.ts
> +const FETCH_NETWORK_TIMEOUT = 15000
не смущает, интересна была мотивация. как насчет сделать что-то вроде зависимости в 2, или 3 раза от базового? так можно их связь сделать

условно
```javascript
const FETCH_CACHED_TIMEOUT = 5000
const FETCH_NETWORK_TIMETOUT = FETCH_CACHED_TIMEOUT * 2
```

2024-01-10 12:13 UTC, AlDmitOl commented on packages/client/src/serviceWorker.ts
> +]
Обычно все вручную прописывают, я не уверен что у нас будет даже больше 5 ассетов. И тут нужно посидеть подумать, так как я с vite я не работал до этого, нужно порыться в документации, как это собрать, просто боюсь тогда эта задача застрянет как минимум до следующего спринта. Нужно определиться со структурой, как будем собирать, будет ли это все с хэшами, без, по каким путям. Я пока не понимаю, как и где мы будем хранить спрайты для движка игры, по каким путям, будут ли звуковые ассеты. Я считаю если это и делать, то как минимум не на этом этапе, а когда будет проект готов к запуску на сайте. По крайней мере такое впечатление сложилось у меня, может я и не прав, буду рад подсказкам.

2024-01-10 12:26 UTC, AlDmitOl commented on packages/client/src/serviceWorker.ts
> +const FETCH_NETWORK_TIMEOUT = 15000
Не вижу смысла. Сервисворкер отдельный файл, который билдится отдельно от основного проекта и как отдельный файл целиком запускается браузером. Он больше не будет дробиться на отдельные модули или расширяться, по крайней мере не более дястка строчек, его константы больше нигде не используются, а так компактно и наглядно, как мне кажется, все храниться в одном файлике. Сразу открываешь и даже не залазя в код, понимаешь, что у тебя будут какие-то таймауты на запросы. Мне кажется это норм в данном случае, если считаете не так, то я поправлю.

2024-01-10 12:31 UTC, AlDmitOl commented on packages/client/src/serviceWorker.ts
> +const FETCH_NETWORK_TIMEOUT = 15000
Хм... интересное предложение, не думал в эту сторону, почему бы и нет. :)

2024-01-10 13:42 UTC, AnastasiaPlague approved these changes

2024-01-10 18:28 UTC, Olegas commented on packages/client/src/serviceWorker.ts
> +        return new Response(FALLBACK_BODY, FALLBACK_HEADERS)
Кажется это спорное решение - на любой запрос где что-то не получилось возвращать успех да еще и типа html. В этом случае пользователь скорее всего не увидит ваше сообщение (кроме разве что открытия начальной страницы), зато получит кучу ошибок (если такая заглушка прилетит вместо, например, js файла
Я бы лучше в случае ошибки (когда нигде ничего не нашлось и ничего не получилось) возвращал честную ошибку (ту, что произошла)

2024-01-10 18:29 UTC, Olegas requested changes
Добрый день.
На мой взгляд решение с заглушкой, которая возвращается при ошибках - очень спорное решение. Написал подробный комментарий почему именно.
Давай обсудим (почему считаешь что так сделать хорошо) или доработаем.

2024-01-10 20:32 UTC, AlDmitOl commented
При написании воркера я смотрел разные статьи, например
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
или
https://habr.com/ru/articles/769170/
В первой сказано, что когда даже резервный ответ недоступен, мы ничего не можем сделать, но мы всегда должны возвращать объект Response, во второй полезная фишка, если мы хотим кастомизировать страницу отсутствия сети, например, хотим поместить туда какую-то полезную информацию или стандартизировать эту страницу для всех пользователей (в разных браузерах разные страницы для отсутствующей сети). Поэтому сделал стандартной, но я согласен, что ответ должен содержать ошибку, что бы это можно было проще обработать.

2024-01-11 06:47 UTC, Olegas approved these changes

2024-01-11 07:15 UTC, merged