REC-40 Настроить Redux и Router в SSR
Sergey-Pavlov809/Pac-Man pull request #37
Opened 2024-02-10 22:26 UTC by AlDmitOl

### Какую задачу решаем

 Настроить Redux и Router в SSR

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-02-11 07:49 UTC, AnastasiaPlague requested changes
добавь меня в соавторы комита

2024-02-11 07:49 UTC, AnastasiaPlague commented on packages/client/server.ts
файл был джсным, а не тс, чтобы не компилировать его дополнительно. сейчас и dev команда не запустится же

2024-02-11 07:49 UTC, AnastasiaPlague commented on packages/client/server.ts
надо команды в пекедже обновить, если тс хочешь оставить

2024-02-11 14:16 UTC, AnastasiaPlague approved these changes

2024-02-12 06:11 UTC, DazzlingFame approved these changes
Привет! Отличная работа! Замечаний нет, реквест принимаю 👍

2024-02-12 17:37 UTC, merged