added forums api
Sergey-Pavlov809/Pac-Man pull request #45
Opened 2024-02-14 08:25 UTC by rkeyrice

- реализовал апи для форума

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-02-14 08:27 UTC, AnastasiaPlague approved these changes

2024-02-14 15:11 UTC, Olegas commented on packages/server/controllers/forum.ts
> +      const user_id = req.body.user.id
Есть ли уже у вас мидлвара, которая проверяет авторизацию? Если да - надо данные о пользователе брать из нее

2024-02-14 15:17 UTC, Olegas requested changes
Добрый день.
Есть замечания - нужно доработать.
Написал подробно комментарии в коде что и где надо поменять.
Кратко:
1. Нет индексов
2. Данные о пользователе берутся с клиента а не из middleware, которая проверяет авторизацию

2024-02-14 15:17 UTC, Olegas commented on packages/server/models/forum.ts
> +  theme_id: {
Не нашел индекса на поле theme_id. Без него поиск сообщений для данной темы будет выполняться не эффективно.

2024-02-14 15:17 UTC, Olegas commented on packages/server/models/forum.ts
> +  theme_id: {
Здесь тоже не хватает индекса - реакции ищутся по ид темы

2024-02-14 19:23 UTC, rkeyrice commented on packages/server/models/forum.ts
> +  theme_id: {
аналогично, как описано выше

2024-02-14 19:25 UTC, rkeyrice commented on packages/server/models/forum.ts
> +  theme_id: {
так это и есть привязка сообщения к теме, далее по этому индексу получаем сообщения конкретной темы
![image](https://github.com/Sergey-Pavlov809/Pac-Man/assets/145926924/5b64e26f-de8c-41cc-832a-bdacfe1a84ad)

2024-02-14 19:27 UTC, rkeyrice commented on packages/server/models/forum.ts
> +  theme_id: {
так это и есть привязка сообщений к конкретной теме, далее по этому индесы получаю сообщения данной темы 
![image](https://github.com/Sergey-Pavlov809/Pac-Man/assets/145926924/7114cba6-5228-4e23-9af8-1739d02b3ffb)

2024-02-14 19:45 UTC, rkeyrice commented on packages/server/controllers/forum.ts
> +      const user_id = req.body.user.id
поправил

2024-02-14 20:11 UTC, Olegas commented on packages/server/models/forum.ts
> +  theme_id: {
Тут нигде нет индекса. Я про индекс в БД с помощью которого ускоряется поиск по таблице

2024-02-14 21:20 UTC, rkeyrice commented on packages/server/models/forum.ts
> +  theme_id: {
Я понял о чем вы, добавил indexes в define схем

2024-02-15 10:12 UTC, Olegas approved these changes
Работа принята

2024-02-15 10:25 UTC, merged