Вёрстка страницы ошибок 400
Sergey-Pavlov809/Pac-Man pull request #6
Opened 2023-12-15 08:31 UTC by AlDmitOl

### Какую задачу решаем

 Вёрстка страницы ошибок 400

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-12-24 12:07 UTC, AnastasiaPlague requested changes

2023-12-24 12:07 UTC, AnastasiaPlague commented on packages/client/src/main.tsx
> +    element: <NotFoundPage />,
в сам ErrorBoundary тоже есть смысл добавить компонент с ошибкой 404

2023-12-24 12:07 UTC, AnastasiaPlague commented on packages/client/src/components/error/ErrorComponent.tsx
> + */
про это уже в пачке коментили, просто подсвечу еще раз

2023-12-24 12:07 UTC, AnastasiaPlague commented on packages/client/src/components/error/ErrorComponent.tsx
> +
можешь пояснить, в чем профит declare здесь? не очень очевидно)

2023-12-24 22:04 UTC, dmitry-aladzyeu commented on packages/client/src/components/error/ErrorComponent.tsx
> +
Забыл убрать)

2023-12-25 07:18 UTC, AnastasiaPlague approved these changes

2024-01-02 16:57 UTC, merged