Feat:(rec 24) Добавил страницу логина
Sergey-Pavlov809/Pac-Man pull request #7
Opened 2023-12-15 11:46 UTC by Sergey-Pavlov809

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-12-16 17:07 UTC, DaoNik commented on packages/client/src/pages/SignIn/SignIn.tsx
> +const onFinish = (values: unknown): undefined => {
Тип для пустых возвращаемых данных обычно делают void(не знаю почему у тебя typescript не ругается)

2023-12-16 17:08 UTC, DaoNik commented on packages/client/src/pages/SignIn/SignIn.tsx
> +function SignIn(): React.FC {
Насколько я понимаю более корректный возвращаемый тип JSX.Element

2023-12-16 17:10 UTC, DaoNik commented on packages/client/src/pages/SignIn/SignIn.tsx
Текст для полей в форме думаю стоит писать на русском(лейблы, ошибки и название кнопки)

2023-12-16 18:56 UTC, AnastasiaPlague commented on packages/client/src/pages/SignIn/Styless.css
> +.container {
если ты юзаешь цсс без модулей, какова гарантия, что никто больше не назовет класс контейнером? предлагаю сделать модуль.цсс

2023-12-16 18:56 UTC, AnastasiaPlague commented on packages/client/src/pages/SignIn/Styless.css
> +  height: 100vh;
не юзай единицы вьюпорта, на сафари проблем не оберешься. проценты лучше

2023-12-16 18:56 UTC, AnastasiaPlague commented on packages/client/src/pages/SignIn/Styless.css
> +  width: 100vw;
топлю за проценты

2023-12-16 18:58 UTC, AnastasiaPlague commented on packages/client/src/index.css
> +  min-width: 1920px;
мы же мобилу будем поддерживать, зачем фиксировать?)

2023-12-16 18:58 UTC, AnastasiaPlague commented on packages/client/src/index.css
> +  font-family: 'PT Root UI', 'Arial', sans-serif;
отказаться, у анта свое семейство шрифтов

2023-12-17 23:10 UTC, AlDmitOl commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      <h1>Авторизация</h1>
В antd есть компонент для добавления заголовков

import { Typography } from 'antd';

const { Title } = Typography;

const App: React.FC = () => (
<>
  <Title>h1. Ant Design</Title>
  <Title level={2}>h2. Ant Design</Title>
  <Title level={3}>h3. Ant Design</Title>
  <Title level={4}>h4. Ant Design</Title>
  <Title level={5}>h5. Ant Design</Title>
</>
);

2023-12-17 23:13 UTC, AlDmitOl commented on packages/client/src/pages/SignIn/SignIn.tsx
> +              { len: 3, message: 'Длинна должна быть больше 3' },
len: 3 - это проверка, что длинна равна 3, для проверки на минимальную и максимальную длину используется min и max

2023-12-17 23:17 UTC, AlDmitOl commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  password?: string
Я думаю, эти поля должны быть обязательными, ты даже проверки делаешь, что поля должны быть

2023-12-17 23:32 UTC, AlDmitOl commented on packages/client/src/pages/SignIn/SignIn.tsx
> +    <div className="container">
Как вариант можно использовать
<Flex
style={{ minHeight: '100%' }}
gap="middle"
align="center"
justify="center"
vertical>
это если придерживаться antd

2023-12-17 23:35 UTC, AlDmitOl commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      <div>
А для чего этот div?

2023-12-21 10:05 UTC, AnastasiaPlague requested changes

2023-12-21 10:05 UTC, AnastasiaPlague commented on packages/client/src/pages/SignIn/SignIn.tsx
> +            { min: 3, message: 'Длинна должна быть больше 3' },
```suggestion
            { min: 3, message: 'Длина должна быть больше 3' },
```

2023-12-21 10:05 UTC, AnastasiaPlague commented on packages/client/src/pages/SignIn/SignIn.tsx
> +            { min: 5, message: 'Длинна должна быть больше 5' },
```suggestion
            { min: 5, message: 'Длина должна быть больше 5' },
```

2023-12-21 10:05 UTC, AnastasiaPlague commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const { Title } = Typography
лучше вынести из компонента под импорты

2023-12-24 16:27 UTC, AnastasiaPlague requested changes
минорные замечания

2023-12-24 16:27 UTC, AnastasiaPlague commented on packages/client/src/main.tsx
> +    path: '/sign-in',
видимо в мерже перетерлось, надо вернуть объект routes

2023-12-24 16:27 UTC, AnastasiaPlague commented on packages/client/src/utils/ruleSchemes.ts
> +  { min: 8, max: 40, message: 'Длинна от 8 до 40' },
```suggestion
  { min: 8, max: 40, message: 'Длина от 8 до 40' },
```

2023-12-24 16:27 UTC, AnastasiaPlague commented on packages/client/src/utils/ruleSchemes.ts
> +  { min: 3, max: 20, message: 'Длинна от 3 до 20' },
```suggestion
  { min: 3, max: 20, message: 'Длина от 3 до 20' },
```

2023-12-24 19:03 UTC, AnastasiaPlague approved these changes

2023-12-25 13:59 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечаний
Поздравляю, апрув 🚀 

Оставил комментарии по улучшению реализации фичи

Хорошего дня :)

2023-12-25 13:59 UTC, IvanPeleshok commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      console.log('Result login', response)
Нужен ли отладочный код в деве?

2023-12-25 13:59 UTC, IvanPeleshok commented on packages/client/src/pages/SignIn/SignIn.tsx
> +    navigate('/sign-up')
Имеет смысл вынести в пути в константы и переиспользовать по необходимости

2023-12-25 13:59 UTC, IvanPeleshok commented on packages/client/src/utils/ruleSchemes.ts
> +const loginValidator: Rule[] = [
Для валидации можно бы было рассмотреть yup: https://github.com/jquense/yup

2023-12-25 16:43 UTC, merged