made the game engine
Sergey-Pavlov809/Pac-Man pull request #8
Opened 2023-12-15 13:01 UTC by rkeyrice

- реализовал движок игры

2023-12-15 13:08 UTC, rkeyrice commented on packages/client/src/pages/Game/useGameinitialization.ts
> +  function circleCollidesWithRectangle({
здесь идет наблюдение на столкновение с границами

2023-12-15 13:10 UTC, rkeyrice commented on packages/client/src/pages/Game/useGameinitialization.ts
> +
в цикле перебираем и смотрим все границы и в случае столкновения убирается скорость

2023-12-15 13:20 UTC, rkeyrice commented on packages/client/src/pages/Game/useGameinitialization.ts
> +      boundary.draw()
рисуется карта

2023-12-16 19:05 UTC, AnastasiaPlague requested changes

2023-12-16 19:05 UTC, AnastasiaPlague commented on packages/client/src/pages/Game/Player.tsx
> +  constructor({ position, velocity, ctx }: PlayerProps) {
напрягает дублирование типов, может как-то иначе протипизировать можно?

2023-12-16 19:05 UTC, AnastasiaPlague commented on packages/client/src/pages/Game/useGameinitialization.ts
> +  }
под это стейт не надо заводить? или ререндер приведет к рестарту игры?

2023-12-16 19:05 UTC, AnastasiaPlague commented on packages/client/src/pages/Game/useGameinitialization.ts
> +    ctx.clearRect(0, 0, 280, 280)
а что за числа здесь? какая то фиксированная позиция? может быть в константы вынести, чтоб не было магических чисел?

2023-12-19 08:56 UTC, rkeyrice commented on packages/client/src/pages/Game/useGameinitialization.ts
> +  }
стейта у нас еще нет никакого

2023-12-19 08:58 UTC, AnastasiaPlague commented on packages/client/src/pages/Game/useGameinitialization.ts
> +  }
то есть в это потом в редакс пойдет?

2023-12-19 08:58 UTC, rkeyrice commented on packages/client/src/pages/Game/useGameinitialization.ts
> +    ctx.clearRect(0, 0, 280, 280)
окей, вынесу

2023-12-19 13:22 UTC, AnastasiaPlague approved these changes

2023-12-19 13:24 UTC, merged